List<String> frasesDeFelicitacion = [
  "¡Excelente trabajo! Estás un paso más cerca de alcanzar tus metas.",
  "¡Increíble! Estás haciendo un gran progreso.",
  "¡Fantástico! Sigue así, cada pequeño paso cuenta.",
  "¡Bravo! Estás construyendo una versión más fuerte y segura de ti mismo.",
  "¡Lo lograste! Celebramos cada logro, por pequeño que sea.",
  "¡Maravilloso! Te estás cuidando y eso es fantástico.",
  "¡Enhorabuena! Estás creciendo y mejorando cada día.",
  "¡Estás en camino! No te detengas, sigamos adelante juntos.",
  "¡Eres increíble! Recuerda siempre lo lejos que has llegado.",
  "¡Sigue así! El esfuerzo que estás poniendo en ti mismo vale la pena.",
  "¡Espectacular! Tu dedicación es admirable.",
  "¡Fabuloso! Cada pequeño avance te acerca más a tu mejor versión.",
  "¡Increíblemente bien hecho! Estás superando tus propios límites.",
  "¡Impresionante! Tu determinación es inspiradora.",
  "¡Fenomenal! No hay límites para lo que puedes lograr.",
  "¡Espléndido! Continúa brillando con tu esfuerzo constante.",
  "¡Extraordinario! Estás haciendo cosas asombrosas.",
  "¡Genial! Tu compromiso contigo mismo es admirable.",
  "¡Fantástico trabajo! Estás haciendo un progreso notable.",
  "¡Maravilloso esfuerzo! Cada paso te acerca más a tus sueños.",
  "¡Brillante! Estás desafiando tus límites y creciendo.",
  "¡Asombroso! Tu determinación es realmente inspiradora.",
  "¡Espectacular trabajo! Estás superando obstáculos con gracia.",
  "¡Increíble progreso! Estás en el camino correcto hacia el éxito.",
  "¡Impresionante esfuerzo! Tu dedicación no pasa desapercibida.",
  "¡Espléndido trabajo! Cada día te vuelves más fuerte y más seguro.",
  "¡Extraordinario progreso! Estás alcanzando nuevas alturas.",
  "¡Genial esfuerzo! Tu constancia te llevará lejos.",
  "¡Fantástico progreso! Estás construyendo un futuro brillante.",
  "¡Maravilloso rendimiento! Tu persistencia está dando frutos.",
  "¡Brillante esfuerzo! Estás demostrando tu verdadero potencial.",
  "¡Asombroso progreso! Tu dedicación merece ser celebrada.",
  "¡Espectacular desempeño! Estás dejando una marca positiva.",
  "¡Increíble determinación! No hay nada que no puedas lograr.",
  "¡Impresionante progreso! Estás superando cada obstáculo.",
  "¡Espléndida dedicación! Tu compromiso es inspirador.",
  "¡Extraordinario esfuerzo! Estás cambiando tu vida para mejor.",
  "¡Genial rendimiento! Cada logro te hace más fuerte.",
  "¡Fantástica perseverancia! Estás en el camino correcto hacia el éxito.",
  "¡Maravilloso progreso! Tu crecimiento es evidente.",
  "¡Brillante trabajo! Estás construyendo un futuro brillante.",
  "¡Asombroso rendimiento! Tu esfuerzo está dando sus frutos.",
  "¡Espectacular progreso! Estás alcanzando tus metas con determinación.",
  "¡Increíble dedicación! Tu persistencia es admirable.",
  "¡Impresionante esfuerzo! Estás avanzando con determinación.",
  "¡Espléndido progreso! Cada paso te acerca más a tus sueños.",
  "¡Extraordinario trabajo! Estás haciendo cosas sorprendentes.",
  "¡Genial rendimiento! Tu compromiso no tiene límites.",
  "¡Fantástico esfuerzo! Estás demostrando tu verdadero potencial.",
  "¡Maravilloso progreso! Cada logro te acerca más a tu mejor versión.",
];
