// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjT9d3G60i7U2MhyUZCelQWdJQhsBg5y8',
    appId: '1:558167798499:web:9000d43bb61cd8ac884bd6',
    messagingSenderId: '558167798499',
    projectId: 'selfraise-51f5b',
    authDomain: 'selfraise-51f5b.firebaseapp.com',
    databaseURL: 'https://selfraise-51f5b-default-rtdb.firebaseio.com',
    storageBucket: 'selfraise-51f5b.appspot.com',
    measurementId: 'G-1W3N49HZ1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrOFeceRLzFp-P-C4Iv_uvrNv_4zZOPzU',
    appId: '1:558167798499:android:2ea08e59ea212f1a884bd6',
    messagingSenderId: '558167798499',
    projectId: 'selfraise-51f5b',
    databaseURL: 'https://selfraise-51f5b-default-rtdb.firebaseio.com',
    storageBucket: 'selfraise-51f5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-ptaRMZzWUR7aP0V5mEH7MPVGmoioIes',
    appId: '1:558167798499:ios:3ae0ff78c0588bc3884bd6',
    messagingSenderId: '558167798499',
    projectId: 'selfraise-51f5b',
    databaseURL: 'https://selfraise-51f5b-default-rtdb.firebaseio.com',
    storageBucket: 'selfraise-51f5b.appspot.com',
    androidClientId: '558167798499-c9ulmvt5is2t0r5bieqn9sq1fubb3vql.apps.googleusercontent.com',
    iosClientId: '558167798499-pohpnunns3enq3mdiipmisorriuarjvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProyectoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-ptaRMZzWUR7aP0V5mEH7MPVGmoioIes',
    appId: '1:558167798499:ios:7bbcdd2b63596106884bd6',
    messagingSenderId: '558167798499',
    projectId: 'selfraise-51f5b',
    databaseURL: 'https://selfraise-51f5b-default-rtdb.firebaseio.com',
    storageBucket: 'selfraise-51f5b.appspot.com',
    androidClientId: '558167798499-c9ulmvt5is2t0r5bieqn9sq1fubb3vql.apps.googleusercontent.com',
    iosClientId: '558167798499-h3pdm9ni8gkt6sdr0vc3la7i4kvb6ehc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProyectoFinal.RunnerTests',
  );
}
